repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
-   repo: https://github.com/ansible/ansible-lint
    rev: v6.9.0
    hooks:
      - id: ansible-lint

